sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - DEPS=latest
        - TEST_COVERAGE=true
    - php: 7.2
      env:
        - DEPS=dev
    - php: 7.3
      env:
        - DEPS=latest
    - php: 7.4
      env:
        - DEPS=latest

before_install:
  - travis_retry php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - travis_retry php composer-setup.php --version=1.10.16

install:
  - if [[ $DEPS == 'dev' ]]; then travis_retry ./composer.phar config minimum-stability dev ; fi
  - if [[ $DEPS == 'latest' || $DEPS == 'dev' ]]; then travis_retry ./composer.phar update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry ./composer.phar update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry ./composer.phar install $COMPOSER_ARGS
  - ./composer.phar show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then ./composer.phar test-coverage ; else composer test ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then php build/coverage-checker.php build/clover.xml 70 ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then php ocular.phar code-coverage:upload --format=php-clover ./build/clover.xml; fi
